src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use \Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Vich\Uploadable
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

	/**
	 * @Vich\UploadableField(mapping="teams_image", fileNameProperty="image")
	 * @var File
	 */
	private $imageFile;

    /**
     * @ORM\ManyToMany(targetEntity=Project::class, inversedBy="users")
     * @JoinTable(name="user_project")
     */
    private $projects;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $jobs;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


	public function getImageFile()
                  	{
                  		return $this->imageFile;
                  	}

	/**
	 * @param \Symfony\Component\HttpFoundation\File\File|null $imageFile
	 */
	public function setImageFile(File $imageFile = null): void
                  	{
                  		$this->imageFile = $imageFile;
                  		if ($imageFile) {
                  			$this->updatedAt = new \DateTime('now');
                  		}
                  
                  	}


	/**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        $this->projects->removeElement($project);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

	public function getFullname(): string
             {
                 return $this->getFirstName().' '.$this->getLastName();
             }

    public function getJobs(): ?string
    {
        return $this->jobs;
    }

    public function setJobs(?string $jobs): self
    {
        $this->jobs = $jobs;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\AboutUs;
use App\Repository\CategoryRepository;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
	public function __construct(
		private readonly EntityManagerInterface $em,
	) {}

	/**
	 * @Route("/", name="home")
	 * @throws \Psr\Cache\InvalidArgumentException
	 */
    public function index( ProjectRepository $repo, CategoryRepository $repoCat ): Response
    {
		$projects = $repo->findBy(
				[],
				['displayOrder' => 'ASC']
			);
        return $this->render('home/index.html.twig', [
            'projects' => $projects,
            'categories' => $repoCat->findAll()
        ]);
    }

	#[Route('/confidentiality', name:'app_privacy_confidentiality')]
	public function privacyConfidentiality(): Response
	{
		$text = $this->em->getRepository(AboutUs::class);
		$confidential = $text->findOneBy(['reference_page' => 'confidential']);
		return $this->render('home/privacyConfidentiality.html.twig',[
			'title' => 'Politique de confidentialité',
			'confidential' => $confidential
		]);
	}
}

templates/home/hiring_page.html.twig
{% extends 'base.html.twig' %}
{% block titel %}{{ parent() }} | {{ title }}{% endblock %}
{% block body %}
	<div class='container mx-auto'>
		<h1 class='text-center my-5'>{{ title }}</h1>
		<div class='d-flex flex-column align-items-center justify-content-center py-5'>
			<div class='col-md-6'>
				<p>Pour le moment nos besoins ne se faisant pas resentir nous vous tennons au courant des
				   prochaines session de recurtement
				</p>
			</div>
		</div>
	</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}dsides{% endblock %}

{% block body %}

<main>
    <div class="container-fluid p-0">
        <div class="row g-0">
            {% for project in projects|filter(project => project.isDisplayed and project.isFeatured) %}
                <div class="col-md-12">
                    {{ include('project/_card_featured.html.twig', {cover: 'cover_420', filter: 'w1600'}) }}
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container-fluid pt-5 pb-5 bg-black">
        <div class="m-5 pt-5 pb-5">
            <h1 class="text-center text-white">DSides accompagne les projets de transformation et de design du travail</h1>
        </div>
    </div>

    <div class="container-fluid p-0 sticky-top f_text_serif">
        <div class="list-group list-group-horizontal justify-content-between text-center overflow-auto" id="list-filter" role="tablist">
                <a class="list-group-item list-group-item-action border-0" data-filter="*">Tout</a>
            {% for category in categories %}
                {% if category.isMenu %}
                    <a class="list-group-item list-group-item-action border-0" data-filter="{{ '.' ~ category.name|slug('_') }}">
                        <span class="align-middle">{{ category.name|capitalize }}</span>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="container-fluid p-0">
        <div id="homeViewArticle" class="grid row row-cols-1 row-cols-md-3 g-0">
            {% for project in projects|filter(project => project.isDisplayed and project.isFeatured == 0) %}
                {% for category in project.category|filter( category => category.isMenu ) %}
                    <div id="cardView" class="col grid-item {{ category.name|slug('_') }}">
                        <div class="card h-100 border-0 rounded-0 bg-white">
                            {{ include('project/_card.html.twig', {cover: 'cover_300', filter: 'w800'}) }}
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('iso') }}
{% endblock %}

templates/home/privacyConfidentiality.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ parent() }} | {{ title }}{% endblock %}

{% block body %}
	<div class='container mx-auto mb-5'>
		<h1 class='fw-bold h1 py-5 my-5 text-center'>{{ title }}</h1>
		<div class='d-flex flex-column justify-content-center align-items-center'>
			<!-- Qui sommes-nous  --->
			<div class='col-md-8 col-sm-8'>
					<h2 class='fw_300 h3'>{{ title }}</h2>
			</div>
			<!-- Utilisation des données --->
			<div class='col-md-8 col-sm-8'>
			{{ confidential.content|raw }}
			</div>
		</div>

	</div>
{% endblock %}

templates/home/teams.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ parent() }} | {{ title }}{% endblock %}

{% block body %}
	<div class='container-fluid bg-team-qsn'></div>
<div class='container'>
	<h1 class='text-center my-5 py-5'>{{ title }}</h1>
	<section class="container mb-5 py-lg-3 py-xl-4 py-xxl-5 font_main">
		<div class='row row-cols-2 row-cols-md-3 g-0 justify-content-center'>
			<!-- Team classique --->
			{% for team in teams %}
			<div class="col pb-3 mx-1" style='width: 19rem'>
				<div class='row row-col-2'>
					<div class='col'>

						<div class="card border-0 bg-transparent">
							<img src="{{ vich_uploader_asset(team, 'imageFile') }}" class="card-img-top rounded-top-0" alt="portrait de {{ team.fullname }}" />
							<div class="card-footer text-center bg-transparent border-0">
								<div class="collapse multi-collapse p-3 bg-gray-200 rounded rounded-1" id="multiCollapse_{{ team.id }}">
									{% if team.content is empty or team.content is null %}
										<p>Un peu de patience, je vous dirais tout, enfin une petite partie de ma bio...</p>
									{% else %}
										{{ team.content }}
									{% endif %}
								</div>
								<button
										class='btn fs-6 p-1 m-1 border-0 text-black mx-auto'
										type="button"
										data-bs-toggle="collapse"
										data-bs-target="#multiCollapse_{{ team.id }}"
										aria-expanded="false"
										aria-controls="multiCollapse_{{ team.id }}">En Savoir +</button>
								<h6 class="card-title">{{ team.fullname }}</h6>
								<p class="card-text fw-bold">{{ team.jobs }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	</section>
</div>
{% endblock %}