src/Entity/AboutUs.php
<?php

namespace App\Entity;

use App\Repository\AboutUsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AboutUsRepository::class)
 */
class AboutUs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference_page;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getReferencePage(): ?string
    {
        return $this->reference_page;
    }

    public function setReferencePage(?string $reference_page): self
    {
        $this->reference_page = $reference_page;

        return $this;
    }
}

src/Controller/AboutUsController.php
<?php

namespace App\Controller;

use App\Repository\AboutUsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AboutUsController extends AbstractController
{
    #[Route('/about/us', name: 'app_about_us')]
    public function index(AboutUsRepository $aboutUsRepository): Response
    {
		$text = $aboutUsRepository->findOneBy(['reference_page' => 'about us']);
        return $this->render('about_us/index.html.twig', [
            'title' => 'Qui sommes nous ?',
            'text' => $text
        ]);
    }
}

templates/about_us/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - {{ title }}{% endblock %}

{% block body %}
	<div class='container-fluid bg-bandeau-qsn'></div>
  <div class='container mx-auto'>
		<h1 class='text-center my-5 py-5'>{{ title }}</h1>
		<div class='d-flex flex-column align-items-center justify-content-center py-5'>
			<div class='col-md-11 text_small_responsive'>
			 {% if text.isPublished is defined and text.isPublished is not null %}
				 <div class='row'>
					 <div class='col-md-5 bg-img-qsn'></div>
					 <div class='col-md-7 text_extra_small px-5'>
						 {{ text.content|raw }}
					 </div>
				 </div>
       {% else %}
         <h2>Dans très peu de temps ici il y aura un text</h2>
       {% endif %}
			</div>
		</div>
	</div>
{% endblock %}